# Site settings
title: Naihui Zhou
url: "http://ashleyzhou972.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 

# Utils
mathjax: true
